<?xml version="1.0"?>
<robot name="grogu"
    xmlns:xacro="http://ros.org/wiki/xacro">
    <xacro:arg name="robot_namespace" default="/" />
    <xacro:arg name="urdf_extras" default="empty.urdf" />
    <xacro:include filename="$(find scout_description)/urdf/grogu_wheel_1.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/grogu_wheel_2.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/grogu_wheel_3.xacro" />
    <xacro:include filename="$(find scout_description)/urdf/grogu_wheel_4.xacro" />
    <!-- Variables -->
    <xacro:property name="M_PI" value="3.14159"/>
    <!-- Vehicle Geometries -->
    <xacro:property name="base_x_size" value="0.6200000" />
    <xacro:property name="base_y_size" value="0.585000" />
    <xacro:property name="base_z_size" value="0.235000" />
    <xacro:property name="wheelbase" value="0.463951"/>
    <xacro:property name="track" value="0.416503"/>
    <xacro:property name="wheel_vertical_offset" value="-0.100998" />
<!--    <xacro:property name="track" value="0.3426" />
    <xacro:property name="wheelbase" value="0.3181"/>
    <xacro:property name="wheel_vertical_offset" value="-0.160000047342231" />-->
    <xacro:property name="wheel_length" value="0.8e-01" />
    <xacro:property name="wheel_radius" value="1.600e-01" />
    <!-- Base link -->
    <link name="base_link">
        <visual>
            <origin
                    xyz="0 0 0.0"
                    rpy="1.57 0 -1.57" />
            <geometry>
                <mesh filename="file://$(find scout_description)/meshes/grogu_base_link2.dae" />
            </geometry>
        </visual>
        <collision>
            <origin
                    xyz="0 0 0"
                    rpy="1.57 0 -1.57" />
          <geometry>
            <mesh filename="file://$(find scout_description)/meshes/grogu_base_link2.dae" />
          </geometry>
        </collision>
    </link>
    <link name="base_scan_lidar">
      <collision name="lidar_sensor_collision">
        <origin xyz="-0.020 0 -0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.0508" length="0.055"/>
        </geometry>
      </collision>
      <visual name="lidar_sensor_visual">
        <origin xyz="-0.032 0 -0.1" rpy="0 0 0"/>
        <geometry>
          <cylinder radius="0.0508" length="0.055"/>
        </geometry>
      </visual>
    </link>
    <link name="base_scan_camera">
      <collision name="camera_collision">
        <origin xyz="0.01 0.0 0.0" rpy="0.0 0.0 0.0"/>
        <geometry>
          <cylinder radius="0.012" length="0.01"/>
        </geometry>
      </collision>
      <visual name="camera_visual">
        <origin xyz="0.01 0.0 0.0" rpy="0.0 ${pi/2} 0.0"/>
        <geometry>
          <cylinder radius="0.012" length="0.01"/>
        </geometry>
      </visual>
    </link>
    <!-- for conversion from ros coords to image -->
    <link name="base_scan_camera_optical"></link>
    <!-- <joint name="chassis_link_joint" type="fixed">
        <origin xyz="0 0 ${wheel_radius - wheel_vertical_offset}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
    </joint> -->
    <link name="inertial_link">
        <inertial>
            <mass value="36" />
            <origin xyz="0.0 0.0 0.0" />
            <inertia ixx="2.288641" ixy="0" ixz="0" iyy="5.103976" iyz="0" izz="3.431465" />
        </inertial>
        <visual name="imu_visual">
        <origin xyz="0.01 0.0 0.2" rpy="0.0 ${pi/2} 0.0"/>
        <geometry>
          <cylinder radius="0.012" length="0.01"/>
        </geometry>
      </visual>
    </link>
    <joint name="inertial_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="inertial_link" />
    </joint>
    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan_lidar"/>
        <origin xyz="-0.032 0 0.171" rpy="0 0 0"/>
    </joint>
    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_scan_camera"/>
        <origin xyz="0.26 0.0 0.03" rpy="0.0 0.0 0.0"/>
    </joint>
    <!-- Translates between ros coords and image direction -->
    <joint name="camera_optical_joint" type="fixed">
        <parent link="base_scan_camera"/>
        <child link="base_scan_camera_optical"/>
        <origin xyz="0.26 0.0 0.03" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>
    <!-- For testing, hang the robot up in the air -->
    <!-- <link name="world" />
    <joint name="world_to_base_link=" type="fixed">
        <origin xyz="0 0 0.5" rpy="0 0 0" />
        <parent link="world"/>
        <child link="base_link"/>
    </joint> -->
    <!-- Scout wheel macros -->
    <!-- wheel labeled from 0 to 3, conter-clockwise, starting from front right wheel -->
    <!-- motor 1 and 2 (left side) are mechanically installed in a reversed direction -->
    <xacro:grogu_wheel_1 wheel_prefix="front_left">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:grogu_wheel_1>
    <xacro:grogu_wheel_2 wheel_prefix="rear_left">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="-1.57 0 0" />
    </xacro:grogu_wheel_2>
    <xacro:grogu_wheel_3 wheel_prefix="front_right">
    <!--<origin
            xyz="0 0 0"
            rpy="0 0 0" />-->
        <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:grogu_wheel_3>
    <xacro:grogu_wheel_4 wheel_prefix="rear_right">
    <!--<origin
           xyz="0 0 0"
           rpy="0 0 0" />-->
        <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset+0.001}" rpy="1.57 0 0" />
    </xacro:grogu_wheel_4>
    <!-- Additional definitions -->
    <xacro:include filename="$(arg urdf_extras)" />
    <!-- Gazebo definitions  -->
    <xacro:include filename="$(find scout_description)/urdf/grogu.gazebo" />
</robot>